server:
  port: 8081
  servlet:
    session:
      cookie:
        name: mmwikissid
      timeout: 20h

spring:
  application:
    name: mmwiki
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mm_wiki?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&sslMode=DISABLED
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123654
    hikari:
      minimum-idle: 10
      maximum-pool-size: 15
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  session:
    store-type: jdbc
    timeout: 1800s
    jdbc:
      initialize-schema: always
  # 设置上传文件大小
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 200MB
  # 设置jackson的默认时区和默认格式
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss



logging:
  file:
    name: logs/mm-wiki.log

mybatis:
  type-aliases-package: org.tinycloud.mmwiki.domain
  configuration:
    map-underscore-to-camel-case: true

mmwiki:
  version: v0.2.1-java-migration
  copyright: 2018 phachon
  system-name-fallback: Markdown Mini Wiki
  document-root-dir: ./data
  search:
    interval-time: 30
    batch-update-doc-num: 100
  author:
    passport: mmwikipassport
    cookie-expired: 72000
